// <auto-generated />
namespace DAL.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ConfiguredTrainerAndCourseTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfiguredTrainerAndCourseTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202004271451138_ConfiguredTrainerAndCourseTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
